### ISSUE TITLE
Use SSD1322 display with out kernel mod

### ISSUE THREAD

**Issue by TssT16** [alidaf/raspberryPi#4]
Hi
you achieved in the past to use the display ssd1322 without modify the kernel right ?
https://github.com/alidaf/raspberryPi/tree/master/displayPi/ssd1322-spi/old

I have successfully compiled the source but the display shows nothing. The wiring is correct and the display works I tested it with arduino.

Have you any suggestions ?
I do not want to modify the kernel because I do not want to update the kernel each time.

**Comment by alidaf** [comment]
Hi,

I managed to get it working but it wasn’t what I had hoped for. I wrote a wiki with exactly what I had to do to get it working on the Raspberry Pi. You may find some help there but it is very specific to the RPi.

https://github.com/alidaf/raspberryPi/wiki/SSD1322(SPI)--fbtft-framebuffer-driver

I’m pretty sure the Arduino has a driver for that display already.

Hope that helps,

Darren

**Comment by TssT16** [comment]
My fold, I wired wrong :(
the end in rasperry pi 2 is not 25 pin -.-
